[package]
name = "rustc_codegen_ssa"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
ar_archive_writer = "0.5"
bitflags = "2.4.1"
bstr = "1.11.3"
find-msvc-tools = "0.1.2"
itertools = "0.12"
pathdiff = "0.2.0"
regex = "1.4"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_arena = { path = "../../../foundation/utils/vitte_arena" }
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_attr_parsing = { path = "../../../lingua/syntax/vitte_attr_parsing" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_fs_util = { path = "../../../foundation/utils/vitte_fs_util" }
rustc_hashes = { path = "../../../foundation/utils/vitte_hashes" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_incremental = { path = "../../../foundation/core/vitte_incremental" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_lint_defs = { path = "../../../foundation/core/vitte_lint_defs" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_metadata = { path = "../../../foundation/utils/vitte_metadata" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_query_system = { path = "../../../foundation/core/vitte_query_system" }
rustc_serialize = { path = "../../../foundation/utils/vitte_serialize" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_symbol_mangling = { path = "../vitte_symbol_mangling" }
rustc_target = { path = "../../../foundation/utils/vitte_target" }
rustc_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
serde_json = "1.0.59"
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
tempfile = "3.2"
thin-vec = "0.2.12"
thorin-dwp = "0.9"
tracing = "0.1"
wasm-encoder = "0.219"
# tidy-alphabetical-end

[target.'cfg(unix)'.dependencies]
# tidy-alphabetical-start
libc = "0.2.50"
# tidy-alphabetical-end

[dependencies.object]
version = "0.37.0"
default-features = false
features = ["read_core", "elf", "macho", "pe", "xcoff", "unaligned", "archive", "write", "wasm"]

[target.'cfg(windows)'.dependencies.windows]
version = "0.61.0"
features = ["Win32_Globalization"]
