[package]
name = "vitte_ty_utils"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
itertools = "0.12"
vitte_abi = { path = "../../../foundation/core/vitte_abi" }
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_errors = { path = "../../../foundation/core/vitte_errors" }
vitte_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
vitte_hashes = { path = "../../../foundation/utils/vitte_hashes" }
vitte_hir = { path = "../vitte_hir" }
vitte_index = { path = "../../../foundation/utils/vitte_index" }
vitte_infer = { path = "../vitte_infer" }
vitte_macros = { path = "../../../foundation/utils/vitte_macros" }
vitte_middle = { path = "../vitte_middle" }
vitte_session = { path = "../../../foundation/core/vitte_session" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
vitte_target = { path = "../../../foundation/utils/vitte_target" }
vitte_trait_selection = { path = "../vitte_trait_selection" }
tracing = "0.1"
# tidy-alphabetical-end
