[package]
name = "vitte_public_bridge"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
vitte_abi = { path = "../vitte_abi" }
vitte_data_structures = { path = "../../utils/vitte_data_structures" }
vitte_hir = { path = "../../../lingua/types/vitte_hir" }
vitte_hir_pretty = { path = "../../../lingua/types/vitte_hir_pretty" }
vitte_middle = { path = "../../../lingua/types/vitte_middle" }
vitte_session = { path = "../vitte_session" }
vitte_span = { path = "../../utils/vitte_span" }
vitte_target = { path = "../../utils/vitte_target" }
# tidy-alphabetical-end
