[package]
name = "rustc_public_bridge"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc_abi = { path = "../vitte_abi" }
rustc_data_structures = { path = "../../utils/vitte_data_structures" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_hir_pretty = { path = "../../../lingua/types/vitte_hir_pretty" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_session = { path = "../vitte_session" }
rustc_span = { path = "../../utils/vitte_span" }
rustc_target = { path = "../../utils/vitte_target" }
# tidy-alphabetical-end
