[package]
name = "rustc_builtin_macros"
version = "0.0.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
# tidy-alphabetical-start
rustc_ast = { path = "../vitte_ast" }
rustc_ast_pretty = { path = "../vitte_ast_pretty" }
rustc_attr_parsing = { path = "../vitte_attr_parsing" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_expand = { path = "../vitte_expand" }
rustc_feature = { path = "../../../foundation/utils/vitte_feature" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_hir = { path = "../../types/vitte_hir" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_lexer = { path = "../vitte_lexer" }
rustc_lint_defs = { path = "../vitte_lint_defs" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_parse = { path = "../vitte_parse" }
rustc_parse_format = { path = "../vitte_parse_format" }
# We must use the proc_macro version that we will compile proc-macros against,
# not the one from our own sysroot.
rustc_proc_macro = { path = "../rustc_proc_macro" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_target = { path = "../../../foundation/utils/vitte_target" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2.12"
tracing = "0.1"
# tidy-alphabetical-end

[features]
# tidy-alphabetical-start
llvm_enzyme = []
# tidy-alphabetical-end
