[package]
name = "rustc_query_impl"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
measureme = "12.0.1"
rustc_data_structures = { path = "../../utils/vitte_data_structures" }
rustc_hashes = { path = "../../utils/vitte_hashes" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_index = { path = "../../utils/vitte_index" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_query_system = { path = "../../../compiler/ir/vitte_query_system" }
rustc_serialize = { path = "../../utils/vitte_serialize" }
rustc_span = { path = "../../utils/vitte_span" }
tracing = "0.1"
# tidy-alphabetical-end
