[package]
name = "rustc_resolve"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
indexmap = "2.4.0"
itertools = "0.12"
pulldown-cmark = { version = "0.11", features = ["html"], default-features = false }
rustc_arena = { path = "../../../foundation/core/vitte_arena" }
rustc_ast = { path = "../../syntax/vitte_ast" }
rustc_ast_pretty = { path = "../../syntax/vitte_ast_pretty" }
rustc_attr_parsing = { path = "../../syntax/vitte_attr_parsing" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_expand = { path = "../../syntax/vitte_expand" }
rustc_feature = { path = "../../../foundation/utils/vitte_feature" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_hir = { path = "../vitte_hir" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_metadata = { path = "../rustc_metadata" }
rustc_middle = { path = "../vitte_middle" }
rustc_query_system = { path = "../../../compiler/ir/vitte_query_system" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2.12"
tracing = "0.1"
# tidy-alphabetical-end
