[package]
name = "rustc_pattern_analysis"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc-hash = "2.0.0"
rustc_abi = { path = "../../../foundation/core/vitte_abi", optional = true }
rustc_apfloat = "0.2.0"
rustc_arena = { path = "../../../foundation/core/vitte_arena", optional = true }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures", optional = true }
rustc_errors = { path = "../../../foundation/core/vitte_errors", optional = true }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro", optional = true }
rustc_hir = { path = "../vitte_hir", optional = true }
rustc_index = { path = "../../../foundation/utils/vitte_index", default-features = false }
rustc_macros = { path = "../../../foundation/utils/vitte_macros", optional = true }
rustc_middle = { path = "../vitte_middle", optional = true }
rustc_session = { path = "../../../foundation/core/vitte_session", optional = true }
rustc_span = { path = "../../../foundation/utils/vitte_span", optional = true }
smallvec = { version = "1.8.1", features = ["union"] }
tracing = "0.1"
# tidy-alphabetical-end

[dev-dependencies]
# tidy-alphabetical-start
tracing-subscriber = { version = "0.3.3", default-features = false, features = ["fmt", "env-filter", "ansi"] }
tracing-tree = "0.3.0"
# tidy-alphabetical-end

[features]
# tidy-alphabetical-start
default = ["rustc"]
rustc = [
    "dep:rustc_abi",
    "dep:rustc_arena",
    "dep:rustc_data_structures",
    "dep:rustc_errors",
    "dep:rustc_fluent_macro",
    "dep:rustc_hir",
    "dep:rustc_macros",
    "dep:rustc_middle",
    "dep:rustc_session",
    "dep:rustc_span",
    "smallvec/may_dangle",
    "rustc_index/nightly",
]
# tidy-alphabetical-end
