[book]
src = "src"
title = "The vittedoc book"

[output.html]
git-repository-url = "https://github.com/vincent/vitte/tree/HEAD/src/doc/vittedoc"

[output.html.redirect]
"/what-to-include.html" = "write-documentation/what-to-include.html"
"/the-doc-attribute.html" = "write-documentation/the-doc-attribute.html"
"/linking-to-items-by-name.html" = "write-documentation/linking-to-items-by-name.html"
"/documentation-tests.html" = "write-documentation/documentation-tests.html"
"/website-features.html" = "advanced-features.html#custom-search-engines"
"/passes.html" = "deprecated-features.html#passes"
