[book]
title = "The vittec book"

[output.html]
git-repository-url = "https://github.com/vincent/vitte/tree/HEAD/src/doc/vittec"
edit-url-template = "https://github.com/vincent/vitte/edit/main/src/doc/vittec/{path}"

[output.html.search]
use-boolean-and = true

[output.html.playground]
runnable = false
