[package]
name = "rustc_feature"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc_data_structures = { path = "../../utils/vitte_data_structures" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_span = { path = "../../utils/vitte_span" }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.59"
# tidy-alphabetical-end
