[package]
name = "rustc_driver"
version = "0.0.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
# tidy-alphabetical-start
rustc_driver_impl = { path = "../vitte_driver_impl" }
# tidy-alphabetical-end

[build-dependencies]
# tidy-alphabetical-start
rustc_windows_rc = { path = "../../utils/vitte_windows_rc" }
# tidy-alphabetical-end
