[package]
name = "rustc_trait_selection"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
itertools = "0.12"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_ast = { path = "../../syntax/vitte_ast" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_hir = { path = "../vitte_hir" }
rustc_infer = { path = "../vitte_infer" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_middle = { path = "../vitte_middle" }
rustc_next_trait_solver = { path = "../vitte_next_trait_solver" }
rustc_parse_format = { path = "../../syntax/vitte_parse_format" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_transmute = { path = "../../../compiler/backends/vitte_transmute", features = ["rustc"] }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2"
tracing = "0.1"
# tidy-alphabetical-end
