[package]
name = "vitte_hir_id"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_index = { path = "../../../foundation/utils/vitte_index" }
vitte_macros = { path = "../../../foundation/utils/vitte_macros" }
vitte_serialize = { path = "../../../foundation/utils/vitte_serialize" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
# tidy-alphabetical-end
