[package]
name = "rustc_hir_id"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_serialize = { path = "../../../foundation/utils/vitte_serialize" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
# tidy-alphabetical-end
