[package]
name = "rustc_middle"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
bitflags = "2.4.1"
either = "1.5.0"
gsgdt = "0.1.2"
polonius-engine = "0.13.0"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_apfloat = "0.2.0"
rustc_arena = { path = "../../../foundation/core/vitte_arena" }
rustc_ast = { path = "../../syntax/vitte_ast" }
rustc_ast_ir = { path = "../../syntax/vitte_ast_ir" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_error_messages = { path = "../../../foundation/core/vitte_error_messages" } # Used for intra-doc links
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_feature = { path = "../../../foundation/utils/vitte_feature" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_graphviz = { path = "../../../foundation/utils/vitte_graphviz" }
rustc_hashes = { path = "../../../foundation/utils/vitte_hashes" }
rustc_hir = { path = "../vitte_hir" }
rustc_hir_pretty = { path = "../vitte_hir_pretty" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_lint_defs = { path = "../../syntax/vitte_lint_defs" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_query_system = { path = "../../../compiler/ir/vitte_query_system" }
rustc_serialize = { path = "../../../foundation/utils/vitte_serialize" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_target = { path = "../../../foundation/utils/vitte_target" }
rustc_thread_pool = { path = "../../../foundation/utils/vitte_thread_pool" }
rustc_type_ir = { path = "../vitte_type_ir" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2.12"
tracing = "0.1"
# tidy-alphabetical-end

[features]
# tidy-alphabetical-start
rustc_randomized_layouts = []
# tidy-alphabetical-end
