[package]
name = "rustc_metadata"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
bitflags = "2.4.1"
libloading = "0.8.0"
odht = { version = "0.3.1", features = ["nightly"] }
rustc_abi = { path = "../../core/vitte_abi" }
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_attr_parsing = { path = "../../../lingua/syntax/vitte_attr_parsing" }
rustc_data_structures = { path = "../vitte_data_structures" }
rustc_errors = { path = "../../core/vitte_errors" }
rustc_expand = { path = "../../../lingua/syntax/vitte_expand" }
rustc_feature = { path = "../../core/vitte_feature" }
rustc_fluent_macro = { path = "../vitte_fluent_macro" }
rustc_fs_util = { path = "../vitte_fs_util" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_hir_pretty = { path = "../../../lingua/types/vitte_hir_pretty" }
rustc_incremental = { path = "../../core/vitte_incremental" }
rustc_index = { path = "../vitte_index" }
rustc_macros = { path = "../vitte_macros" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
# We must use the proc_macro version that we will compile proc-macros against,
# not the one from our own sysroot.
rustc_proc_macro = { path = "../vitte_proc_macro" }
rustc_serialize = { path = "../vitte_serialize" }
rustc_session = { path = "../../core/vitte_session" }
rustc_span = { path = "../vitte_span" }
rustc_target = { path = "../vitte_target" }
tempfile = "3.7.1"
tracing = "0.1"
# tidy-alphabetical-end

[target.'cfg(target_os = "aix")'.dependencies]
# tidy-alphabetical-start
libc = "0.2"
# tidy-alphabetical-end
