[package]
name = "rustc_symbol_mangling"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
punycode = "0.4.0"
rustc-demangle = "0.1.21"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_hashes = { path = "../../../foundation/utils/vitte_hashes" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
tracing = "0.1"
# tidy-alphabetical-end
