[package]
name = "vitte_serialize"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
indexmap = "2.0.0"
vitte_hashes = { path = "../vitte_hashes" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2.12"
# tidy-alphabetical-end

[dev-dependencies]
# tidy-alphabetical-start
vitte_macros = { path = "../vitte_macros" }
tempfile = "3.2"
# tidy-alphabetical-end
