[package]
name = "vitte_ast_pretty"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
itertools = "0.12"
vitte_ast = { path = "../vitte_ast" }
vitte_lexer = { path = "../vitte_lexer" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
# tidy-alphabetical-end

[dev-dependencies]
# tidy-alphabetical-start
thin-vec = "0.2.12"
# tidy-alphabetical-end
