[package]
name = "rustc_mir_build"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
itertools = "0.12"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_apfloat = "0.2.0"
rustc_arena = { path = "../../../foundation/core/vitte_arena" }
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_infer = { path = "../../../lingua/types/vitte_infer" }
rustc_lint = { path = "../../../lingua/syntax/vitte_lint" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_pattern_analysis = { path = "../../../lingua/types/vitte_pattern_analysis" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
tracing = "0.1"
# tidy-alphabetical-end
