[package]
name = "vitte_mir_build"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
itertools = "0.12"
vitte_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_apfloat = "0.2.0"
vitte_arena = { path = "../../../foundation/utils/vitte_arena" }
vitte_ast = { path = "../../../lingua/syntax/vitte_ast" }
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_errors = { path = "../../../foundation/core/vitte_errors" }
vitte_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
vitte_hir = { path = "../../../lingua/types/vitte_hir" }
vitte_index = { path = "../../../foundation/utils/vitte_index" }
vitte_infer = { path = "../../../lingua/types/vitte_infer" }
vitte_lint = { path = "../../../foundation/core/vitte_lint" }
vitte_macros = { path = "../../../foundation/utils/vitte_macros" }
vitte_middle = { path = "../../../lingua/types/vitte_middle" }
vitte_pattern_analysis = { path = "../../../lingua/types/vitte_pattern_analysis" }
vitte_session = { path = "../../../foundation/core/vitte_session" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
vitte_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
tracing = "0.1"
# tidy-alphabetical-end
