[package]
name = "rustc_const_eval"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
either = "1"
rustc_abi = { path = "../vitte_abi" }
rustc_apfloat = "0.2.0"
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_data_structures = { path = "../../utils/vitte_data_structures" }
rustc_errors = { path = "../vitte_errors" }
rustc_fluent_macro = { path = "../../utils/vitte_fluent_macro" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_index = { path = "../../utils/vitte_index" }
rustc_infer = { path = "../../../lingua/types/vitte_infer" }
rustc_macros = { path = "../../utils/vitte_macros" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_mir_dataflow = { path = "../../../compiler/ir/vitte_mir_dataflow" }
rustc_session = { path = "../vitte_session" }
rustc_span = { path = "../../utils/vitte_span" }
rustc_target = { path = "../../utils/vitte_target" }
rustc_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
tracing = "0.1"
# tidy-alphabetical-end
