[package]
name = "vitte_bench"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
vitte_common = { path = "../vitte_common" }

[dev-dependencies]
criterion = "0.5"

[lib]
name = "vitte_bench"
path = "src/lib.rs"

[[bin]]
name = "vitte_bench_cli"
path = "src/bin/cli.rs"
