[package]
name = "vitte_sanitizers"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
bitflags = "2.5.0"
vitte_abi = { path = "../../../foundation/core/vitte_abi" }
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_hir = { path = "../../../lingua/types/vitte_hir" }
vitte_middle = { path = "../../../lingua/types/vitte_middle" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
vitte_target = { path = "../../../foundation/utils/vitte_target" }
vitte_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
tracing = "0.1"
twox-hash = "1.6.3"
# tidy-alphabetical-end
