[package]
name = "rustc_sanitizers"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
bitflags = "2.5.0"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_target = { path = "../../../foundation/utils/vitte_target" }
rustc_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
tracing = "0.1"
twox-hash = "1.6.3"
# tidy-alphabetical-end
