[package]
name = "vitte_infer"
version = "0.0.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
# tidy-alphabetical-start
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_errors = { path = "../../../foundation/core/vitte_errors" }
vitte_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
vitte_hir = { path = "../vitte_hir" }
vitte_index = { path = "../../../foundation/utils/vitte_index" }
vitte_macros = { path = "../../../foundation/utils/vitte_macros" }
vitte_middle = { path = "../vitte_middle" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
vitte_type_ir = { path = "../vitte_type_ir" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2.12"
tracing = "0.1"
# tidy-alphabetical-end
