[package]
name = "rustc_infer"
version = "0.0.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
# tidy-alphabetical-start
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_hir = { path = "../vitte_hir" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_middle = { path = "../vitte_middle" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_type_ir = { path = "../vitte_type_ir" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2.12"
tracing = "0.1"
# tidy-alphabetical-end
