# vitte/rust/crates/vitte_regex/Cargo.toml

[package]
name = "vitte_regex"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Regex wrapper crate for the Vitte ecosystem."
repository = "https://github.com/vitte-lang/vitte"

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = ["vitte_common/std"]

[dependencies]
vitte_common = { path = "../vitte_common", default-features = true }
regex = "1"
bitflags = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
