[package]
name = "vitte_regex"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
regex_crate = ["dep:regex"]

[dependencies]
regex = { version = "1", optional = true }
