# vitte/rust/crates/vitte_fmt/Cargo.toml

[package]
name = "vitte_fmt"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Vitte formatter tool (CLI)."
repository = "https://github.com//vitte-lang-vitte"

[dependencies]
vitte_common = { path = "../vitte_common", default-features = true }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
