[package]
name = "vitte_fmt"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "vittefmt"
path = "src/main.rs"

[dependencies]
vitte_muf = { path = "../vitte_muf" }
