[package]
name = "vitte_span"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
bitflags = "2.4.1"
blake3 = "1.5.2"
derive-where = "1.2.7"
indexmap = { version = "2.0.0" }
itoa = "1.0"
md5 = { package = "md-5", version = "0.10.0" }
vitte_arena = { path = "../../utils/vitte_arena" }
vitte_data_structures = { path = "../../utils/vitte_data_structures" }
vitte_hashes = { path = "../../utils/vitte_hashes" }
vitte_index = { path = "../../utils/vitte_index" }
vitte_macros = { path = "../../utils/vitte_macros" }
vitte_serialize = { path = "../../utils/vitte_serialize" }
scoped-tls = "1.0"
sha1 = "0.10.0"
sha2 = "0.10.1"
tracing = "0.1"
unicode-width = "0.2.2"
# tidy-alphabetical-end
