[package]
name = "vitte_driver_impl"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
jiff = { version = "0.2.5", default-features = false, features = ["std"] }
vitte_abi = { path = "../vitte_abi" }
vitte_ast = { path = "../../../lingua/syntax/vitte_ast" }
vitte_ast_lowering = { path = "../../../lingua/syntax/vitte_ast_lowering" }
vitte_ast_passes = { path = "../../../lingua/syntax/vitte_ast_passes" }
vitte_ast_pretty = { path = "../../../lingua/syntax/vitte_ast_pretty" }
vitte_attr_parsing = { path = "../../../lingua/syntax/vitte_attr_parsing" }
vitte_borrowck = { path = "../../../lingua/types/vitte_borrowck" }
vitte_builtin_macros = { path = "../../../lingua/syntax/vitte_builtin_macros" }
vitte_codegen_ssa = { path = "../../../compiler/backends/vitte_codegen_ssa" }
vitte_const_eval = { path = "../vitte_const_eval" }
vitte_data_structures = { path = "../../utils/vitte_data_structures" }
vitte_errors = { path = "../vitte_errors" }
vitte_expand = { path = "../../../lingua/syntax/vitte_expand" }
vitte_feature = { path = "../vitte_feature" }
vitte_fluent_macro = { path = "../../utils/vitte_fluent_macro" }
vitte_hir_analysis = { path = "../../../lingua/types/vitte_hir_analysis" }
vitte_hir_pretty = { path = "../../../lingua/types/vitte_hir_pretty" }
vitte_hir_typeck = { path = "../../../lingua/types/vitte_hir_typeck" }
vitte_incremental = { path = "../vitte_incremental" }
vitte_index = { path = "../../utils/vitte_index" }
vitte_infer = { path = "../../../lingua/types/vitte_infer" }
vitte_interface = { path = "../vitte_interface" }
vitte_lint = { path = "../vitte_lint" }
vitte_log = { path = "../../utils/vitte_log" }
vitte_macros = { path = "../../utils/vitte_macros" }
vitte_metadata = { path = "../../utils/vitte_metadata" }
vitte_middle = { path = "../../../lingua/types/vitte_middle" }
vitte_mir_build = { path = "../../../compiler/backends/vitte_mir_build" }
vitte_mir_dataflow = { path = "../../../compiler/backends/vitte_mir_dataflow" }
vitte_mir_transform = { path = "../../../compiler/backends/vitte_mir_transform" }
vitte_monomorphize = { path = "../../../compiler/backends/vitte_monomorphize" }
vitte_parse = { path = "../../../lingua/syntax/vitte_parse" }
vitte_passes = { path = "../../../lingua/syntax/vitte_passes" }
vitte_pattern_analysis = { path = "../../../lingua/types/vitte_pattern_analysis" }
vitte_privacy = { path = "../../../lingua/types/vitte_privacy" }
vitte_public = { path = "../vitte_public", features = ["rustc_internal"] }
vitte_query_system = { path = "../vitte_query_system" }
vitte_resolve = { path = "../../../lingua/types/vitte_resolve" }
vitte_session = { path = "../vitte_session" }
vitte_span = { path = "../../utils/vitte_span" }
vitte_target = { path = "../../utils/vitte_target" }
vitte_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
vitte_ty_utils = { path = "../../../lingua/types/vitte_ty_utils" }
serde_json = "1.0.59"
shlex = "1.0"
tracing = { version = "0.1.35" }
# tidy-alphabetical-end

[target.'cfg(all(unix, any(target_env = "gnu", target_os = "macos")))'.dependencies]
# tidy-alphabetical-start
libc = "0.2"
# tidy-alphabetical-end

[target.'cfg(windows)'.dependencies.windows]
version = "0.61.0"
features = [
    "Win32_System_Diagnostics_Debug",
]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
# tidy-alphabetical-start
ctrlc = "3.4.4"
# tidy-alphabetical-end

[features]
# tidy-alphabetical-start
check_only = ['rustc_interface/check_only']
llvm = ['rustc_interface/llvm']
llvm_enzyme = ['rustc_interface/llvm_enzyme']
llvm_offload = ['rustc_interface/llvm_offload']
max_level_info = ['rustc_log/max_level_info']
rustc_randomized_layouts = [
    'rustc_index/rustc_randomized_layouts',
    'rustc_middle/rustc_randomized_layouts'
]
# tidy-alphabetical-end
