[package]
name = "rustc_driver_impl"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
jiff = { version = "0.2.5", default-features = false, features = ["std"] }
rustc_abi = { path = "../vitte_abi" }
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_ast_lowering = { path = "../../../lingua/syntax/vitte_ast_lowering" }
rustc_ast_passes = { path = "../../../lingua/syntax/vitte_ast_passes" }
rustc_ast_pretty = { path = "../../../lingua/syntax/vitte_ast_pretty" }
rustc_attr_parsing = { path = "../../../lingua/syntax/vitte_attr_parsing" }
rustc_borrowck = { path = "../../../lingua/types/vitte_borrowck" }
rustc_builtin_macros = { path = "../../../lingua/syntax/vitte_builtin_macros" }
rustc_codegen_ssa = { path = "../../../compiler/backends/vitte_codegen_ssa" }
rustc_const_eval = { path = "../vitte_const_eval" }
rustc_data_structures = { path = "../../utils/vitte_data_structures" }
rustc_errors = { path = "../vitte_errors" }
rustc_expand = { path = "../../../lingua/syntax/vitte_expand" }
rustc_feature = { path = "../vitte_feature" }
rustc_fluent_macro = { path = "../../utils/vitte_fluent_macro" }
rustc_hir_analysis = { path = "../../../lingua/types/vitte_hir_analysis" }
rustc_hir_pretty = { path = "../../../lingua/types/vitte_hir_pretty" }
rustc_hir_typeck = { path = "../../../lingua/types/vitte_hir_typeck" }
rustc_incremental = { path = "../vitte_incremental" }
rustc_index = { path = "../../utils/vitte_index" }
rustc_infer = { path = "../../../lingua/types/vitte_infer" }
rustc_interface = { path = "../vitte_interface" }
rustc_lint = { path = "../vitte_lint" }
rustc_log = { path = "../../utils/vitte_log" }
rustc_macros = { path = "../../utils/vitte_macros" }
rustc_metadata = { path = "../../utils/vitte_metadata" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_mir_build = { path = "../../../compiler/backends/vitte_mir_build" }
rustc_mir_dataflow = { path = "../../../compiler/backends/vitte_mir_dataflow" }
rustc_mir_transform = { path = "../../../compiler/backends/vitte_mir_transform" }
rustc_monomorphize = { path = "../../../compiler/backends/vitte_monomorphize" }
rustc_parse = { path = "../../../lingua/syntax/vitte_parse" }
rustc_passes = { path = "../../../lingua/syntax/vitte_passes" }
rustc_pattern_analysis = { path = "../../../lingua/types/vitte_pattern_analysis" }
rustc_privacy = { path = "../../../lingua/types/vitte_privacy" }
rustc_public = { path = "../vitte_public", features = ["rustc_internal"] }
rustc_query_system = { path = "../vitte_query_system" }
rustc_resolve = { path = "../../../lingua/types/vitte_resolve" }
rustc_session = { path = "../vitte_session" }
rustc_span = { path = "../../utils/vitte_span" }
rustc_target = { path = "../../utils/vitte_target" }
rustc_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
rustc_ty_utils = { path = "../../../lingua/types/vitte_ty_utils" }
serde_json = "1.0.59"
shlex = "1.0"
tracing = { version = "0.1.35" }
# tidy-alphabetical-end

[target.'cfg(all(unix, any(target_env = "gnu", target_os = "macos")))'.dependencies]
# tidy-alphabetical-start
libc = "0.2"
# tidy-alphabetical-end

[target.'cfg(windows)'.dependencies.windows]
version = "0.61.0"
features = [
    "Win32_System_Diagnostics_Debug",
]

[target.'cfg(not(target_family = "wasm"))'.dependencies]
# tidy-alphabetical-start
ctrlc = "3.4.4"
# tidy-alphabetical-end

[features]
# tidy-alphabetical-start
check_only = ['rustc_interface/check_only']
llvm = ['rustc_interface/llvm']
llvm_enzyme = ['rustc_interface/llvm_enzyme']
llvm_offload = ['rustc_interface/llvm_offload']
max_level_info = ['rustc_log/max_level_info']
rustc_randomized_layouts = [
    'rustc_index/rustc_randomized_layouts',
    'rustc_middle/rustc_randomized_layouts'
]
# tidy-alphabetical-end
