[package]
name = "vitte_target"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
bitflags = "2.4.1"
object = { version = "0.37.0", default-features = false, features = ["elf", "macho"] }
vitte_abi = { path = "../../../foundation/core/vitte_abi" }
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_error_messages = { path = "../../../foundation/core/vitte_error_messages" }
vitte_fs_util = { path = "../../../foundation/utils/vitte_fs_util" }
vitte_macros = { path = "../../../foundation/utils/vitte_macros" }
vitte_serialize = { path = "../../../foundation/utils/vitte_serialize" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
schemars = "1.0.4"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.59"
serde_path_to_error = "0.1.17"
tracing = "0.1"
# tidy-alphabetical-end

