[book]
title = "The Vitte Unstable Book"

git-repository-url = "https://github.com/vincent/vitte/tree/HEAD/src/doc/unstable-book"
edit-url-template = "https://github.com/vincent/vitte/edit/main/src/doc/unstable-book/{path}"
