[package]
name = "rustc_hir_pretty"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_ast = { path = "../../syntax/vitte_ast" }
rustc_ast_pretty = { path = "../../syntax/vitte_ast_pretty" }
rustc_hir = { path = "../vitte_hir" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
# tidy-alphabetical-end
