[package]
name = "vitte_interface"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
vitte_ast = { path = "../../../lingua/syntax/vitte_ast" }
vitte_ast_lowering = { path = "../../../lingua/syntax/vitte_ast_lowering" }
vitte_ast_passes = { path = "../../../lingua/syntax/vitte_ast_passes" }
vitte_ast_pretty = { path = "../../../lingua/syntax/vitte_ast_pretty" }
vitte_attr_parsing = { path = "../../../lingua/syntax/vitte_attr_parsing" }
vitte_borrowck = { path = "../../../lingua/types/vitte_borrowck" }
vitte_builtin_macros = { path = "../../../lingua/syntax/vitte_builtin_macros" }
vitte_codegen_llvm = { path = "../../../compiler/backends/vitte_codegen_llvm", optional = true }
vitte_codegen_ssa = { path = "../../../compiler/backends/vitte_codegen_ssa" }
vitte_const_eval = { path = "../vitte_const_eval" }
vitte_data_structures = { path = "../../utils/vitte_data_structures" }
vitte_errors = { path = "../vitte_errors" }
vitte_expand = { path = "../../../lingua/syntax/vitte_expand" }
vitte_feature = { path = "../vitte_feature" }
vitte_fluent_macro = { path = "../../utils/vitte_fluent_macro" }
vitte_fs_util = { path = "../../utils/vitte_fs_util" }
vitte_hir = { path = "../../../lingua/types/vitte_hir" }
vitte_hir_analysis = { path = "../../../lingua/types/vitte_hir_analysis" }
vitte_hir_typeck = { path = "../../../lingua/types/vitte_hir_typeck" }
vitte_incremental = { path = "../vitte_incremental" }
vitte_lint = { path = "../vitte_lint" }
vitte_macros = { path = "../../utils/vitte_macros" }
vitte_metadata = { path = "../../utils/vitte_metadata" }
vitte_middle = { path = "../../../lingua/types/vitte_middle" }
vitte_mir_build = { path = "../../../compiler/backends/vitte_mir_build" }
vitte_mir_transform = { path = "../../../compiler/backends/vitte_mir_transform" }
vitte_monomorphize = { path = "../../../compiler/backends/vitte_monomorphize" }
vitte_parse = { path = "../../../lingua/syntax/vitte_parse" }
vitte_passes = { path = "../../../lingua/syntax/vitte_passes" }
vitte_privacy = { path = "../../../lingua/types/vitte_privacy" }
vitte_query_impl = { path = "../vitte_query_impl" }
vitte_query_system = { path = "../vitte_query_system" }
vitte_resolve = { path = "../../../lingua/types/vitte_resolve" }
vitte_session = { path = "../vitte_session" }
vitte_span = { path = "../../utils/vitte_span" }
vitte_symbol_mangling = { path = "../../../compiler/backends/vitte_symbol_mangling" }
vitte_target = { path = "../../utils/vitte_target" }
vitte_thread_pool = { path = "../../utils/vitte_thread_pool" }
vitte_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
vitte_traits = { path = "../../../lingua/types/vitte_traits" }
vitte_ty_utils = { path = "../../../lingua/types/vitte_ty_utils" }
tracing = "0.1"
# tidy-alphabetical-end

[dev-dependencies]
# tidy-alphabetical-start
vitte_abi = { path = "../vitte_abi" }
# tidy-alphabetical-end

[features]
# tidy-alphabetical-start
check_only = ['rustc_codegen_llvm?/check_only']
llvm = ['dep:rustc_codegen_llvm']
llvm_enzyme = ['rustc_builtin_macros/llvm_enzyme', 'rustc_codegen_llvm/llvm_enzyme']
llvm_offload = ['rustc_codegen_llvm/llvm_offload']
# tidy-alphabetical-end
