[package]
name = "rustc_interface"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_ast_lowering = { path = "../../../lingua/syntax/vitte_ast_lowering" }
rustc_ast_passes = { path = "../../../lingua/syntax/vitte_ast_passes" }
rustc_ast_pretty = { path = "../../../lingua/syntax/vitte_ast_pretty" }
rustc_attr_parsing = { path = "../../../lingua/syntax/vitte_attr_parsing" }
rustc_borrowck = { path = "../../../lingua/types/vitte_borrowck" }
rustc_builtin_macros = { path = "../../../lingua/syntax/vitte_builtin_macros" }
rustc_codegen_llvm = { path = "../../../compiler/backends/vitte_codegen_llvm", optional = true }
rustc_codegen_ssa = { path = "../../../compiler/backends/vitte_codegen_ssa" }
rustc_const_eval = { path = "../../../compiler/ir/vitte_const_eval" }
rustc_data_structures = { path = "../../utils/vitte_data_structures" }
rustc_errors = { path = "../vitte_errors" }
rustc_expand = { path = "../../../lingua/syntax/vitte_expand" }
rustc_feature = { path = "../../utils/vitte_feature" }
rustc_fluent_macro = { path = "../../utils/vitte_fluent_macro" }
rustc_fs_util = { path = "../../utils/vitte_fs_util" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_hir_analysis = { path = "../../../lingua/types/vitte_hir_analysis" }
rustc_hir_typeck = { path = "../../../lingua/types/vitte_hir_typeck" }
rustc_incremental = { path = "../../../compiler/ir/vitte_incremental" }
rustc_lint = { path = "../../../lingua/syntax/vitte_lint" }
rustc_macros = { path = "../../utils/vitte_macros" }
rustc_metadata = { path = "../rustc_metadata" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_mir_build = { path = "../../../compiler/ir/vitte_mir_build" }
rustc_mir_transform = { path = "../../../compiler/ir/vitte_mir_transform" }
rustc_monomorphize = { path = "../../../compiler/ir/vitte_monomorphize" }
rustc_parse = { path = "../../../lingua/syntax/vitte_parse" }
rustc_passes = { path = "../../../lingua/syntax/vitte_passes" }
rustc_privacy = { path = "../../../lingua/types/vitte_privacy" }
rustc_query_impl = { path = "../../../compiler/ir/vitte_query_impl" }
rustc_query_system = { path = "../../../compiler/ir/vitte_query_system" }
rustc_resolve = { path = "../../../lingua/types/vitte_resolve" }
rustc_session = { path = "../vitte_session" }
rustc_span = { path = "../../utils/vitte_span" }
rustc_symbol_mangling = { path = "../../../compiler/backends/vitte_symbol_mangling" }
rustc_target = { path = "../../utils/vitte_target" }
rustc_thread_pool = { path = "../../utils/vitte_thread_pool" }
rustc_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
rustc_traits = { path = "../../../lingua/types/vitte_traits" }
rustc_ty_utils = { path = "../../../lingua/types/vitte_ty_utils" }
tracing = "0.1"
# tidy-alphabetical-end

[dev-dependencies]
# tidy-alphabetical-start
rustc_abi = { path = "../vitte_abi" }
# tidy-alphabetical-end

[features]
# tidy-alphabetical-start
check_only = ['rustc_codegen_llvm?/check_only']
llvm = ['dep:rustc_codegen_llvm']
llvm_enzyme = ['rustc_builtin_macros/llvm_enzyme', 'rustc_codegen_llvm/llvm_enzyme']
llvm_offload = ['rustc_codegen_llvm/llvm_offload']
# tidy-alphabetical-end
