# vitte/rust/crates/vitte_lsp/Cargo.toml

[package]
name = "vitte_lsp"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Language Server Protocol (LSP) server for Vitte."
repository = "https://github.com/vitte-lang/vitte"

[[bin]]
name = "vitte-lsp"
path = "src/main.rs"

[dependencies]
vitte_common = { path = "../vitte_common", default-features = true }

tokio = { version = "1", features = ["rt-multi-thread", "macros", "io-std"] }
tower-lsp = "0.20"
url = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
