[package]
name = "vitte_session"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
getopts = "0.2"
rand = "0.9.0"
vitte_abi = { path = "../vitte_abi" }
vitte_ast = { path = "../../../lingua/syntax/vitte_ast" }
vitte_data_structures = { path = "../../utils/vitte_data_structures" }
vitte_errors = { path = "../vitte_errors" }
vitte_feature = { path = "../vitte_feature" }
vitte_fluent_macro = { path = "../../utils/vitte_fluent_macro" }
vitte_fs_util = { path = "../../utils/vitte_fs_util" }
vitte_hashes = { path = "../../utils/vitte_hashes" }
vitte_hir = { path = "../../../lingua/types/vitte_hir" }
vitte_lint_defs = { path = "../vitte_lint_defs" }
vitte_macros = { path = "../../utils/vitte_macros" }
vitte_serialize = { path = "../../utils/vitte_serialize" }
vitte_span = { path = "../../utils/vitte_span" }
vitte_target = { path = "../../utils/vitte_target" }
termize = "0.2"
tracing = "0.1"
# tidy-alphabetical-end

[target.'cfg(unix)'.dependencies]
# tidy-alphabetical-start
libc = "0.2"
# tidy-alphabetical-end

[target.'cfg(windows)'.dependencies.windows]
version = "0.61.0"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
]
