[package]
name = "rustc_session"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
getopts = "0.2"
rand = "0.9.0"
rustc_abi = { path = "../vitte_abi" }
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_data_structures = { path = "../../utils/vitte_data_structures" }
rustc_errors = { path = "../vitte_errors" }
rustc_feature = { path = "../../utils/vitte_feature" }
rustc_fluent_macro = { path = "../../utils/vitte_fluent_macro" }
rustc_fs_util = { path = "../../utils/vitte_fs_util" }
rustc_hashes = { path = "../../utils/vitte_hashes" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_lint_defs = { path = "../../../lingua/syntax/vitte_lint_defs" }
rustc_macros = { path = "../../utils/vitte_macros" }
rustc_serialize = { path = "../../utils/vitte_serialize" }
rustc_span = { path = "../../utils/vitte_span" }
rustc_target = { path = "../../utils/vitte_target" }
termize = "0.2"
tracing = "0.1"
# tidy-alphabetical-end

[target.'cfg(unix)'.dependencies]
# tidy-alphabetical-start
libc = "0.2"
# tidy-alphabetical-end

[target.'cfg(windows)'.dependencies.windows]
version = "0.61.0"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
]
