[package]
name = "rustc_lint_defs"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_data_structures = { path = "../../utils/vitte_data_structures" }
rustc_error_messages = { path = "../vitte_error_messages" }
rustc_hir_id = { path = "../../../lingua/types/vitte_hir_id" }
rustc_macros = { path = "../../utils/vitte_macros" }
rustc_serialize = { path = "../../utils/vitte_serialize" }
rustc_span = { path = "../../utils/vitte_span" }
serde = { version = "1.0.125", features = ["derive"] }
# tidy-alphabetical-end
