[package]
name = "rustc_mir_transform"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
either = "1"
hashbrown = "0.15"
itertools = "0.12"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_arena = { path = "../../../foundation/core/vitte_arena" }
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_const_eval = { path = "../../ir/vitte_const_eval" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_infer = { path = "../../../lingua/types/vitte_infer" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_mir_build = { path = "../../ir/vitte_mir_build" }
rustc_mir_dataflow = { path = "../../ir/vitte_mir_dataflow" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_target = { path = "../../../foundation/utils/vitte_target" }
rustc_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
tracing = "0.1"
# tidy-alphabetical-end
