[package]
name = "rustc_passes"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_ast = { path = "../vitte_ast" }
rustc_ast_lowering = { path = "../vitte_ast_lowering" }
rustc_attr_parsing = { path = "../vitte_attr_parsing" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_expand = { path = "../vitte_expand" }
rustc_feature = { path = "../../../foundation/core/vitte_feature" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_hir = { path = "../../types/vitte_hir" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_middle = { path = "../../types/vitte_middle" }
rustc_privacy = { path = "../../types/vitte_privacy" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_target = { path = "../../../foundation/utils/vitte_target" }
rustc_trait_selection = { path = "../../types/vitte_trait_selection" }
tracing = "0.1"
# tidy-alphabetical-end
