[package]
name = "vitte_passes"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
vitte_abi = { path = "../../../foundation/core/vitte_abi" }
vitte_ast = { path = "../vitte_ast" }
vitte_ast_lowering = { path = "../vitte_ast_lowering" }
vitte_attr_parsing = { path = "../vitte_attr_parsing" }
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_errors = { path = "../../../foundation/core/vitte_errors" }
vitte_expand = { path = "../vitte_expand" }
vitte_feature = { path = "../../../foundation/core/vitte_feature" }
vitte_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
vitte_hir = { path = "../../types/vitte_hir" }
vitte_index = { path = "../../../foundation/utils/vitte_index" }
vitte_macros = { path = "../../../foundation/utils/vitte_macros" }
vitte_middle = { path = "../../types/vitte_middle" }
vitte_privacy = { path = "../../types/vitte_privacy" }
vitte_session = { path = "../../../foundation/core/vitte_session" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
vitte_target = { path = "../../../foundation/utils/vitte_target" }
vitte_trait_selection = { path = "../../types/vitte_trait_selection" }
tracing = "0.1"
# tidy-alphabetical-end
