[package]
name = "vitte_privacy"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
vitte_ast = { path = "../../syntax/vitte_ast" }
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_errors = { path = "../../../foundation/core/vitte_errors" }
vitte_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
vitte_hir = { path = "../vitte_hir" }
vitte_macros = { path = "../../../foundation/utils/vitte_macros" }
vitte_middle = { path = "../vitte_middle" }
vitte_session = { path = "../../../foundation/core/vitte_session" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
vitte_ty_utils = { path = "../vitte_ty_utils" }
tracing = "0.1"
# tidy-alphabetical-end
