[package]
name = "rustc_privacy"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc_ast = { path = "../../syntax/vitte_ast" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_hir = { path = "../vitte_hir" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_middle = { path = "../vitte_middle" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_ty_utils = { path = "../vitte_ty_utils" }
tracing = "0.1"
# tidy-alphabetical-end
