[package]
name = "rustc_ast_passes"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
itertools = "0.12"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_ast = { path = "../vitte_ast" }
rustc_ast_pretty = { path = "../vitte_ast_pretty" }
rustc_attr_parsing = { path = "../vitte_attr_parsing" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_feature = { path = "../../../foundation/utils/vitte_feature" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_target = { path = "../../../foundation/utils/vitte_target" }
thin-vec = "0.2.12"
# tidy-alphabetical-end
