[package]
name = "vitte_ast_passes"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
itertools = "0.12"
vitte_abi = { path = "../../../foundation/core/vitte_abi" }
vitte_ast = { path = "../vitte_ast" }
vitte_ast_pretty = { path = "../vitte_ast_pretty" }
vitte_attr_parsing = { path = "../vitte_attr_parsing" }
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_errors = { path = "../../../foundation/core/vitte_errors" }
vitte_feature = { path = "../../../foundation/core/vitte_feature" }
vitte_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
vitte_macros = { path = "../../../foundation/utils/vitte_macros" }
vitte_session = { path = "../../../foundation/core/vitte_session" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
vitte_target = { path = "../../../foundation/utils/vitte_target" }
thin-vec = "0.2.12"
# tidy-alphabetical-end
