[package]
name = "rustc_lint"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
bitflags = "2.4.1"
rustc_abi = { path = "../vitte_abi" }
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_ast_pretty = { path = "../../../lingua/syntax/vitte_ast_pretty" }
rustc_attr_parsing = { path = "../../../lingua/syntax/vitte_attr_parsing" }
rustc_data_structures = { path = "../../utils/vitte_data_structures" }
rustc_errors = { path = "../vitte_errors" }
rustc_feature = { path = "../vitte_feature" }
rustc_fluent_macro = { path = "../../utils/vitte_fluent_macro" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_index = { path = "../../utils/vitte_index" }
rustc_infer = { path = "../../../lingua/types/vitte_infer" }
rustc_macros = { path = "../../utils/vitte_macros" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_parse_format = { path = "../../../lingua/syntax/vitte_parse_format" }
rustc_session = { path = "../vitte_session" }
rustc_span = { path = "../../utils/vitte_span" }
rustc_target = { path = "../../utils/vitte_target" }
rustc_trait_selection = { path = "../../../lingua/types/vitte_trait_selection" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
tracing = "0.1"
unicode-security = "0.1.0"
# tidy-alphabetical-end
