[package]
name = "rustc_codegen_llvm"
version = "0.0.0"
edition = "2024"

[lib]
test = false

[dependencies]
# tidy-alphabetical-start
bitflags = "2.4.1"
# To avoid duplicate dependencies, this should match the version of gimli used
# by `rustc_codegen_ssa` via its `thorin-dwp` dependency.
gimli = "0.31"
itertools = "0.12"
libc = "0.2"
libloading = { version = "0.9.0" }
measureme = "12.0.1"
object = { version = "0.37.0", default-features = false, features = ["std", "read"] }
rustc-demangle = "0.1.21"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_codegen_ssa = { path = "../vitte_codegen_ssa" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_fs_util = { path = "../../../foundation/utils/vitte_fs_util" }
rustc_hashes = { path = "../../../foundation/utils/vitte_hashes" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_llvm = { path = "../vitte_llvm" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_metadata = { path = "../../../foundation/utils/vitte_metadata" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_query_system = { path = "../../../foundation/core/vitte_query_system" }
rustc_sanitizers = { path = "../../../foundation/utils/vitte_sanitizers" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_symbol_mangling = { path = "../vitte_symbol_mangling" }
rustc_target = { path = "../../../foundation/utils/vitte_target" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
tracing = "0.1"
# tidy-alphabetical-end

[features]
# tidy-alphabetical-start
check_only = ["rustc_llvm/check_only"]
llvm_enzyme = []
llvm_offload = []
# tidy-alphabetical-end

