[package]
name = "vitte_borrowck"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
either = "1.5.0"
itertools = "0.12"
polonius-engine = "0.13.0"
vitte_abi = { path = "../../../foundation/core/vitte_abi" }
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_errors = { path = "../../../foundation/core/vitte_errors" }
vitte_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
vitte_graphviz = { path = "../../../foundation/utils/vitte_graphviz" }
vitte_hir = { path = "../vitte_hir" }
vitte_index = { path = "../../../foundation/utils/vitte_index" }
vitte_infer = { path = "../vitte_infer" }
vitte_lexer = { path = "../../syntax/vitte_lexer" }
vitte_macros = { path = "../../../foundation/utils/vitte_macros" }
vitte_middle = { path = "../vitte_middle" }
vitte_mir_dataflow = { path = "../../../compiler/backends/vitte_mir_dataflow" }
vitte_session = { path = "../../../foundation/core/vitte_session" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
vitte_trait_selection = { path = "../vitte_trait_selection" }
vitte_traits = { path = "../vitte_traits" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
tracing = "0.1"
# tidy-alphabetical-end
