[package]
name = "rustc_borrowck"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
either = "1.5.0"
itertools = "0.12"
polonius-engine = "0.13.0"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_graphviz = { path = "../../../foundation/utils/vitte_graphviz" }
rustc_hir = { path = "../vitte_hir" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_infer = { path = "../vitte_infer" }
rustc_lexer = { path = "../../syntax/vitte_lexer" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_middle = { path = "../vitte_middle" }
rustc_mir_dataflow = { path = "../../../compiler/ir/vitte_mir_dataflow" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_trait_selection = { path = "../vitte_trait_selection" }
rustc_traits = { path = "../vitte_traits" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
tracing = "0.1"
# tidy-alphabetical-end
