[package]
name = "rustc_mir_dataflow"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
polonius-engine = "0.13.0"
regex = "1"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_graphviz = { path = "../../../foundation/utils/vitte_graphviz" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
tracing = "0.1"
# tidy-alphabetical-end
