[package]
name = "vitte_traits"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_infer = { path = "../vitte_infer" }
vitte_middle = { path = "../vitte_middle" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
vitte_trait_selection = { path = "../vitte_trait_selection" }
tracing = "0.1"
# tidy-alphabetical-end
