[package]
name = "rustc_traits"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_infer = { path = "../vitte_infer" }
rustc_middle = { path = "../vitte_middle" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_trait_selection = { path = "../vitte_trait_selection" }
tracing = "0.1"
# tidy-alphabetical-end
