[package]
name = "rustc_hir_typeck"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
itertools = "0.12"
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_ast = { path = "../../syntax/vitte_ast" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_hir = { path = "../vitte_hir" }
rustc_hir_analysis = { path = "../vitte_hir_analysis" }
rustc_hir_pretty = { path = "../vitte_hir_pretty" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_infer = { path = "../vitte_infer" }
rustc_lint = { path = "../../../foundation/core/vitte_lint" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_middle = { path = "../vitte_middle" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_target = { path = "../../../foundation/utils/vitte_target" }
rustc_trait_selection = { path = "../vitte_trait_selection" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
tracing = "0.1"
# tidy-alphabetical-end
