[package]
name = "rustc_parse"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
bitflags = "2.4.1"
rustc-literal-escaper = "0.0.5"
rustc_ast = { path = "../vitte_ast" }
rustc_ast_pretty = { path = "../vitte_ast_pretty" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_errors = { path = "../../../foundation/core/vitte_errors" }
rustc_feature = { path = "../../../foundation/core/vitte_feature" }
rustc_fluent_macro = { path = "../../../foundation/utils/vitte_fluent_macro" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_lexer = { path = "../vitte_lexer" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_session = { path = "../../../foundation/core/vitte_session" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
thin-vec = "0.2.12"
tracing = "0.1"
unicode-normalization = "0.1.25"
unicode-width = "0.2.2"
# tidy-alphabetical-end

[dev-dependencies]
# tidy-alphabetical-start
# tidy-alphabetical-end
