[package]
name = "vitte_index"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
vitte_index_macros = { path = "../vitte_index_macros" }
vitte_macros = { path = "../vitte_macros", optional = true }
vitte_serialize = { path = "../vitte_serialize", optional = true }
smallvec = { version = "1.8.1", optional = true }
# tidy-alphabetical-end

[features]
# tidy-alphabetical-start
default = ["nightly"]
nightly = [
    "dep:rustc_macros",
    "dep:rustc_serialize",
    "dep:smallvec",
    "rustc_index_macros/nightly",
]
rustc_randomized_layouts = []
# tidy-alphabetical-end
