[package]
name = "rustc_incremental"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rand = "0.9.0"
rustc_ast = { path = "../../../lingua/syntax/vitte_ast" }
rustc_data_structures = { path = "../../utils/vitte_data_structures" }
rustc_errors = { path = "../vitte_errors" }
rustc_fluent_macro = { path = "../../utils/vitte_fluent_macro" }
rustc_fs_util = { path = "../../utils/vitte_fs_util" }
rustc_graphviz = { path = "../../utils/vitte_graphviz" }
rustc_hashes = { path = "../../utils/vitte_hashes" }
rustc_hir = { path = "../../../lingua/types/vitte_hir" }
rustc_macros = { path = "../../utils/vitte_macros" }
rustc_middle = { path = "../../../lingua/types/vitte_middle" }
rustc_serialize = { path = "../../utils/vitte_serialize" }
rustc_session = { path = "../vitte_session" }
rustc_span = { path = "../../utils/vitte_span" }
thin-vec = "0.2.12"
tracing = "0.1"
# tidy-alphabetical-end
