[package]
name = "vitte_incremental"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rand = "0.9.0"
vitte_ast = { path = "../../../lingua/syntax/vitte_ast" }
vitte_data_structures = { path = "../../utils/vitte_data_structures" }
vitte_errors = { path = "../vitte_errors" }
vitte_fluent_macro = { path = "../../utils/vitte_fluent_macro" }
vitte_fs_util = { path = "../../utils/vitte_fs_util" }
vitte_graphviz = { path = "../../utils/vitte_graphviz" }
vitte_hashes = { path = "../../utils/vitte_hashes" }
vitte_hir = { path = "../../../lingua/types/vitte_hir" }
vitte_macros = { path = "../../utils/vitte_macros" }
vitte_middle = { path = "../../../lingua/types/vitte_middle" }
vitte_serialize = { path = "../../utils/vitte_serialize" }
vitte_session = { path = "../vitte_session" }
vitte_span = { path = "../../utils/vitte_span" }
thin-vec = "0.2.12"
tracing = "0.1"
# tidy-alphabetical-end
