[target.'cfg(all(target_arch = "aarch64", target_os = "linux"))']
'F32Array::conv_c'.busted = "check"

[target.'cfg(all(target_arch = "aarch64", target_os = "macos"))']
'SingleVariantUnion::conv_c::repr_c'.busted = "check"
'OptionU128::conv_::repr_c::c_caller'.busted = "run"
'OptionU128::conv_::repr_c::cgclif_caller'.busted = "check"

[target.'cfg(all(target_arch = "x86_64", windows))']
'simple::conv_'.busted = "check"
'simple::conv_::c_caller'.busted = "run"

[target.'*'.'f16']
run = "skip"

[target.'*'.'f128']
run = "skip"
