[package]
name = "vitte_parse_format"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
rustc-literal-escaper = "0.0.5"
vitte_lexer = { path = "../vitte_lexer" }
# tidy-alphabetical-end

[target.'cfg(target_pointer_width = "64")'.dev-dependencies]
# tidy-alphabetical-start
vitte_index = { path = "../../../foundation/utils/vitte_index", default-features = false }
# tidy-alphabetical-end
