[package]
name = "rustc_hir"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
bitflags = "2.9.1"
odht = { version = "0.3.1", features = ["nightly"] }
rustc_abi = { path = "../../../foundation/core/vitte_abi" }
rustc_arena = { path = "../../../foundation/core/vitte_arena" }
rustc_ast = { path = "../../syntax/vitte_ast" }
rustc_ast_pretty = { path = "../../syntax/vitte_ast_pretty" }
rustc_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
rustc_error_messages = { path = "../../../foundation/core/vitte_error_messages" }
rustc_hashes = { path = "../../../foundation/utils/vitte_hashes" }
rustc_hir_id = { path = "../vitte_hir_id" }
rustc_index = { path = "../../../foundation/utils/vitte_index" }
rustc_lint_defs = { path = "../../syntax/vitte_lint_defs" }
rustc_macros = { path = "../../../foundation/utils/vitte_macros" }
rustc_serialize = { path = "../../../foundation/utils/vitte_serialize" }
rustc_span = { path = "../../../foundation/utils/vitte_span" }
rustc_target = { path = "../../../foundation/utils/vitte_target" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2.12"
tracing = "0.1"
# tidy-alphabetical-end
