[package]
name = "vitte_hir"
version = "0.0.0"
edition = "2024"

[dependencies]
# tidy-alphabetical-start
bitflags = "2.9.1"
odht = { version = "0.3.1", features = ["nightly"] }
vitte_abi = { path = "../../../foundation/core/vitte_abi" }
vitte_arena = { path = "../../../foundation/utils/vitte_arena" }
vitte_ast = { path = "../../syntax/vitte_ast" }
vitte_ast_pretty = { path = "../../syntax/vitte_ast_pretty" }
vitte_data_structures = { path = "../../../foundation/utils/vitte_data_structures" }
vitte_error_messages = { path = "../../../foundation/core/vitte_error_messages" }
vitte_hashes = { path = "../../../foundation/utils/vitte_hashes" }
vitte_hir_id = { path = "../vitte_hir_id" }
vitte_index = { path = "../../../foundation/utils/vitte_index" }
vitte_lint_defs = { path = "../../../foundation/core/vitte_lint_defs" }
vitte_macros = { path = "../../../foundation/utils/vitte_macros" }
vitte_serialize = { path = "../../../foundation/utils/vitte_serialize" }
vitte_span = { path = "../../../foundation/utils/vitte_span" }
vitte_target = { path = "../../../foundation/utils/vitte_target" }
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2.12"
tracing = "0.1"
# tidy-alphabetical-end
